<a href="https://colab.research.google.com/github/ggpukar/pukarban/blob/main/grammerchecker.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import language_tool_python
import spacy

print("Libraries installed successfully!")

Libraries installed successfully!

In [ ]:
tool = language_tool_python.LanguageTool("en-US")

print("Grammar checker ready!")

Downloading LanguageTool 6.8: 100%|██████████| 259M/259M [00:02<00:00, 99.8MB/s]

Grammar checker ready!

In [ ]:
text = "She go to school every day."

matches = tool.check(text)

print("Number of errors:", len(matches))

for match in matches:
    print("Error:", match.message)
    print("Suggestion:", match.replacements[:3])
    print("Position:", match.offset, "-", match.offset + match.error_length)
    print()

Number of errors: 1
Error: The pronoun ‘She’ is usually used with a third-person or a past tense verb.
Suggestion: ['goes', 'went']
Position: 4 - 6

In [ ]:
corrected_text = language_tool_python.utils.correct(text, matches)

print("Original:")
print(text)

print("\nCorrected:")
print(corrected_text)

Original:
She go to school every day.

Corrected:
She goes to school every day.

In [ ]:
def categorize_error(match):
    message = match.message.lower()

    if "pronoun" in message and "third-person" in message:
        return "Subject-Verb Agreement"

    if "subject" in message and "verb" in message:
        return "Subject-Verb Agreement"

    if "spelling" in message or "misspelled" in message:
        return "Spelling"

    if "article" in message or "determiner" in message:
        return "Article/Determiner"

    if "preposition" in message:
        return "Preposition"

    if "tense" in message or "past tense" in message:
        return "Verb Tense"

    if "punctuation" in message:
        return "Punctuation"

    if "capital" in message:
        return "Capitalization"

    return "Other Grammar"

In [ ]:
text = "She go to school every day."

matches = tool.check(text)

for match in matches:
    error = text[match.offset:match.offset + match.error_length]
    category = categorize_error(match)

    print("❌ Error:", error)
    print("✅ Suggestions:", match.replacements[:3])
    print("📌 Category:", category)
    print("📝 Message:", match.message)
    print("📍 Position:", match.offset)

❌ Error: go
✅ Suggestions: ['goes', 'went']
📌 Category: Subject-Verb Agreement
📝 Message: The pronoun ‘She’ is usually used with a third-person or a past tense verb.
📍 Position: 4

In [ ]:
def calculate_confidence(match):
    score = 50

    # More than one correction means lower certainty
    if len(match.replacements) == 1:
        score += 30
    elif len(match.replacements) == 2:
        score += 20
    elif len(match.replacements) >= 3:
        score += 10

    # Grammar rules with a clear message
    if match.message:
        score += 10

    # Keep score between 0 and 100
    return min(score, 100)

In [ ]:
text = "She go to school every day."

matches = tool.check(text)

for match in matches:
    error = text[match.offset:match.offset + match.error_length]
    category = categorize_error(match)
    confidence = calculate_confidence(match)

    print("❌ Error:", error)
    print("✅ Suggestions:", match.replacements[:3])
    print("📌 Category:", category)
    print("📊 Confidence:", str(confidence) + "%")
    print("📝 Message:", match.message)
    print("-" * 50)

❌ Error: go
✅ Suggestions: ['goes', 'went']
📌 Category: Subject-Verb Agreement
📊 Confidence: 80%
📝 Message: The pronoun ‘She’ is usually used with a third-person or a past tense verb.
--------------------------------------------------

In [ ]:
test_sentences = [
    "She go to school every day.",
    "He eat rice yesterday.",
    "They is playing football.",
    "I has a new book.",
    "She have an apple."
]

for text in test_sentences:

    print("\nOriginal:", text)

    matches = tool.check(text)

    if not matches:
        print("✅ No errors found.")
        continue

    for match in matches:
        error = text[match.offset:match.offset + match.error_length]
        category = categorize_error(match)
        confidence = calculate_confidence(match)

        print("❌ Error:", error)
        print("✅ Suggestions:", match.replacements[:3])
        print("📌 Category:", category)
        print("📊 Confidence:", str(confidence) + "%")

Original: She go to school every day.
❌ Error: go
✅ Suggestions: ['goes', 'went']
📌 Category: Subject-Verb Agreement
📊 Confidence: 80%

Original: He eat rice yesterday.
❌ Error: eat
✅ Suggestions: ['eats', 'ate']
📌 Category: Subject-Verb Agreement
📊 Confidence: 80%

Original: They is playing football.
❌ Error: is
✅ Suggestions: ['are', 'were']
📌 Category: Other Grammar
📊 Confidence: 80%

Original: I has a new book.
❌ Error: has
✅ Suggestions: ['have']
📌 Category: Other Grammar
📊 Confidence: 90%

Original: She have an apple.
❌ Error: have
✅ Suggestions: ['has', 'had']
📌 Category: Subject-Verb Agreement
📊 Confidence: 80%

In [ ]:
def analyze_text(text):
    matches = tool.check(text)

    results = []

    for match in matches:
        error = text[match.offset:match.offset + match.error_length]
        category = categorize_error(match)
        confidence = calculate_confidence(match)

        results.append({
            "error": error,
            "suggestions": match.replacements[:3],
            "category": category,
            "confidence": confidence,
            "message": match.message,
            "position": match.offset
        })

    corrected_text = language_tool_python.utils.correct(text, matches)

    return {
        "original": text,
        "corrected": corrected_text,
        "errors": results,
        "total_errors": len(results)
    }

In [ ]:
text = "She go to school every day."

result = analyze_text(text)

print("ORIGINAL:")
print(result["original"])

print("\nCORRECTED:")
print(result["corrected"])

print("\nTOTAL ERRORS:")
print(result["total_errors"])

print("\nERROR DETAILS:")

for error in result["errors"]:
    print("\n❌ Error:", error["error"])
    print("✅ Suggestions:", error["suggestions"])
    print("📌 Category:", error["category"])
    print("📊 Confidence:", str(error["confidence"]) + "%")

ORIGINAL:
She go to school every day.

CORRECTED:
She goes to school every day.

TOTAL ERRORS:
1

ERROR DETAILS:

❌ Error: go
✅ Suggestions: ['goes', 'went']
📌 Category: Subject-Verb Agreement
📊 Confidence: 80%

In [ ]:
print("=" * 60)
print("           AI GRAMMAR CHECKER")
print("=" * 60)

print("\nBEFORE:")
print(result["original"])

print("\nAFTER:")
print(result["corrected"])

print("\nDETECTED ERRORS:")
print("-" * 60)

for i, error in enumerate(result["errors"], start=1):
    print(f"\nError {i}")
    print("Wrong word   :", error["error"])
    print("Suggestion   :", error["suggestions"][0] if error["suggestions"] else "No suggestion")
    print("Category     :", error["category"])
    print("Confidence   :", str(error["confidence"]) + "%")

============================================================
           AI GRAMMAR CHECKER
============================================================

BEFORE:
She go to school every day.

AFTER:
She goes to school every day.

DETECTED ERRORS:
------------------------------------------------------------

Error 1
Wrong word   : go
Suggestion   : goes
Category     : Subject-Verb Agreement
Confidence   : 80%

In [ ]:
test_data = [
    "She go to school every day.",
    "He eat rice yesterday.",
    "They is playing football.",
    "I has a new book.",
    "She have an apple.",
    "He don't like coffee.",
    "I am go to college.",
    "She have two brother.",
    "They was happy.",
    "He play football every Sunday."
]

print("Total test sentences:", len(test_data))

Total test sentences: 10

In [ ]:
for i, text in enumerate(test_data, start=1):

    result = analyze_text(text)

    print("=" * 70)
    print(f"Sentence {i}")
    print("Original  :", result["original"])
    print("Corrected :", result["corrected"])
    print("Errors    :", result["total_errors"])

    for error in result["errors"]:
        suggestion = (
            error["suggestions"][0]
            if error["suggestions"]
            else "No suggestion"
        )

        print("  ❌ Error      :", error["error"])
        print("  ✅ Suggestion :", suggestion)
        print("  📌 Category   :", error["category"])
        print("  📊 Confidence :", str(error["confidence"]) + "%")

======================================================================
Sentence 1
Original  : She go to school every day.
Corrected : She goes to school every day.
Errors    : 1
  ❌ Error      : go
  ✅ Suggestion : goes
  📌 Category   : Subject-Verb Agreement
  📊 Confidence : 80%
======================================================================
Sentence 2
Original  : He eat rice yesterday.
Corrected : He eats rice yesterday.
Errors    : 1
  ❌ Error      : eat
  ✅ Suggestion : eats
  📌 Category   : Subject-Verb Agreement
  📊 Confidence : 80%
======================================================================
Sentence 3
Original  : They is playing football.
Corrected : They are playing football.
Errors    : 1
  ❌ Error      : is
  ✅ Suggestion : are
  📌 Category   : Other Grammar
  📊 Confidence : 80%
======================================================================
Sentence 4
Original  : I has a new book.
Corrected : I have a new book.
Errors    : 1
  ❌ Error      : has
  ✅ Suggestion : have
  📌 Category   : Other Grammar
  📊 Confidence : 90%
======================================================================
Sentence 5
Original  : She have an apple.
Corrected : She has an apple.
Errors    : 1
  ❌ Error      : have
  ✅ Suggestion : has
  📌 Category   : Subject-Verb Agreement
  📊 Confidence : 80%
======================================================================
Sentence 6
Original  : He don't like coffee.
Corrected : He doesn't like coffee.
Errors    : 1
  ❌ Error      : do
  ✅ Suggestion : does
  📌 Category   : Subject-Verb Agreement
  📊 Confidence : 80%
======================================================================
Sentence 7
Original  : I am go to college.
Corrected : I am going to college.
Errors    : 1
  ❌ Error      : I am go
  ✅ Suggestion : I am going
  📌 Category   : Other Grammar
  📊 Confidence : 90%
======================================================================
Sentence 8
Original  : She have two brother.
Corrected : She has two brethren.
Errors    : 2
  ❌ Error      : have
  ✅ Suggestion : has
  📌 Category   : Subject-Verb Agreement
  📊 Confidence : 80%
  ❌ Error      : brother
  ✅ Suggestion : brethren
  📌 Category   : Other Grammar
  📊 Confidence : 80%
======================================================================
Sentence 9
Original  : They was happy.
Corrected : They are happy.
Errors    : 1
  ❌ Error      : was
  ✅ Suggestion : are
  📌 Category   : Other Grammar
  📊 Confidence : 80%
======================================================================
Sentence 10
Original  : He play football every Sunday.
Corrected : He plays football every Sunday.
Errors    : 1
  ❌ Error      : play
  ✅ Suggestion : plays
  📌 Category   : Subject-Verb Agreement
  📊 Confidence : 80%

In [ ]:
import pandas as pd

rows = []

for text in test_data:

    result = analyze_text(text)

    if result["errors"]:
        for error in result["errors"]:

            suggestion = (
                error["suggestions"][0]
                if error["suggestions"]
                else ""
            )

            rows.append({
                "Original": text,
                "Corrected": result["corrected"],
                "Error": error["error"],
                "Suggestion": suggestion,
                "Category": error["category"],
                "Confidence": error["confidence"]
            })

    else:
        rows.append({
            "Original": text,
            "Corrected": result["corrected"],
            "Error": "",
            "Suggestion": "",
            "Category": "No Error",
            "Confidence": 100
        })

df = pd.DataFrame(rows)

df

,Original,Corrected,Error,Suggestion,Category,Confidence
0,She go to school every day.,She goes to school every day.,go,goes,Subject-Verb Agreement,80
1,He eat rice yesterday.,He eats rice yesterday.,eat,eats,Subject-Verb Agreement,80
2,They is playing football.,They are playing football.,is,are,Other Grammar,80
3,I has a new book.,I have a new book.,has,have,Other Grammar,90
4,She have an apple.,She has an apple.,have,has,Subject-Verb Agreement,80
5,He don't like coffee.,He doesn't like coffee.,do,does,Subject-Verb Agreement,80
6,I am go to college.,I am going to college.,I am go,I am going,Other Grammar,90
7,She have two brother.,She has two brethren.,have,has,Subject-Verb Agreement,80
8,She have two brother.,She has two brethren.,brother,brethren,Other Grammar,80
9,They was happy.,They are happy.,was,are,Other Grammar,80
10,He play football every Sunday.,He plays football every Sunday.,play,plays,Subject-Verb Agreement,80

In [ ]:
print("Error Category Summary:")
print(df["Category"].value_counts())

Error Category Summary:
Category
Subject-Verb Agreement    6
Other Grammar             5
Name: count, dtype: int64

In [ ]:
!pip install -q kagglehub

In [ ]:
import kagglehub

kagglehub.login()

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggle…

Kaggle credentials set.
Kaggle credentials successfully validated.

In [ ]:
import kagglehub

dataset_path = kagglehub.dataset_download(
    "hammad9191/english-proofreadingmessage-stylejfleg-filtered"
)

print("Dataset downloaded to:")
print(dataset_path)

Downloading to /root/.cache/kagglehub/datasets/hammad9191/english-proofreadingmessage-stylejfleg-filtered/1.archive...

100%|██████████| 74.1k/74.1k [00:00<00:00, 10.6MB/s]

Extracting files...
Dataset downloaded to:
/root/.cache/kagglehub/datasets/hammad9191/english-proofreadingmessage-stylejfleg-filtered/versions/1

In [ ]:
import os

for root, dirs, files in os.walk(dataset_path):
    for file in files:
        print(os.path.join(root, file))

/root/.cache/kagglehub/datasets/hammad9191/english-proofreadingmessage-stylejfleg-filtered/versions/1/README.md
/root/.cache/kagglehub/datasets/hammad9191/english-proofreadingmessage-stylejfleg-filtered/versions/1/english-proofreading-dataset/data_test.csv
/root/.cache/kagglehub/datasets/hammad9191/english-proofreadingmessage-stylejfleg-filtered/versions/1/english-proofreading-dataset/README.md
/root/.cache/kagglehub/datasets/hammad9191/english-proofreadingmessage-stylejfleg-filtered/versions/1/english-proofreading-dataset/data_train.csv
/root/.cache/kagglehub/datasets/hammad9191/english-proofreadingmessage-stylejfleg-filtered/versions/1/english-proofreading-dataset/data_valid.csv

In [ ]:
import os

print("Files in dataset folder:")

for file in os.listdir(dataset_path):
    print(file)

Files in dataset folder:
english-proofreading-dataset
README.md

In [ ]:
import os

dataset_folder = os.path.join(dataset_path, "english-proofreading-dataset")

print("Files inside english-proofreading-dataset:")

for file in os.listdir(dataset_folder):
    print(file)

Files inside english-proofreading-dataset:
data_test.csv
README.md
data_train.csv
data_valid.csv

In [ ]:
import pandas as pd
import os

dataset_folder = os.path.join(
    dataset_path,
    "english-proofreading-dataset"
)

train_file = os.path.join(dataset_folder, "data_train.csv")
valid_file = os.path.join(dataset_folder, "data_valid.csv")
test_file = os.path.join(dataset_folder, "data_test.csv")

train_df = pd.read_csv(train_file)
valid_df = pd.read_csv(valid_file)
test_df = pd.read_csv(test_file)

print("Training dataset shape:", train_df.shape)
print("Validation dataset shape:", valid_df.shape)
print("Testing dataset shape:", test_df.shape)

Training dataset shape: (0, 5)
Validation dataset shape: (650, 5)
Testing dataset shape: (626, 5)

In [ ]:
print("Training columns:")
print(train_df.columns.tolist())

print("\nFirst 5 rows:")
display(train_df.head())

Training columns:
['id', 'split', 'source', 'target', 'domain']

First 5 rows:

Empty DataFrame
Columns: [id, split, source, target, domain]
Index: []

In [ ]:
print("Train shape:", train_df.shape)
print("Validation shape:", valid_df.shape)
print("Test shape:", test_df.shape)

print("\nRows in each dataset:")
print("Train:", len(train_df))
print("Validation:", len(valid_df))
print("Test:", len(test_df))

Train shape: (0, 5)
Validation shape: (650, 5)
Test shape: (626, 5)

Rows in each dataset:
Train: 0
Validation: 650
Test: 626

In [ ]:
import os

for file in [train_file, valid_file, test_file]:
    print(
        os.path.basename(file),
        "->",
        os.path.getsize(file),
        "bytes"
    )

data_train.csv -> 30 bytes
data_valid.csv -> 140175 bytes
data_test.csv -> 139502 bytes

In [ ]:
for name, file in [
    ("TRAIN", train_file),
    ("VALIDATION", valid_file),
    ("TEST", test_file)
]:
    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)

    with open(file, "r", encoding="utf-8") as f:
        print(f.read(500))

============================================================
TRAIN
============================================================
id,split,source,target,domain


============================================================
VALIDATION
============================================================
id,split,source,target,domain
dev_1,dev,So I think we can not live if old people could not find siences and tecnologies and they did not developped .,So I think we would not be alive if our ancestors did not develop sciences and technologies .,message-like
dev_2,dev,For not use car .,Not for use with a car .,message-like
dev_3,dev,Here was no promise of morning except that we looked up through the trees we saw how low the forest had swung .,"Here was no promise of morning , except that we looked

============================================================
TEST
============================================================
id,split,source,target,domain
test_651,test,New and new technology has been introduced to the society .,New technology has been introduced to society .,message-like
test_652,test,One possible outcome is that an environmentally-induced reduction in motorization levels in the richer countries will outweigh any rise in motorization levels in the poorer countries .,One possible outcome is that an environmentally-induced reduction in motorization levels in richer countries will outweigh any rise in m

In [ ]:
print("Training:", len(train_df))
print("Validation:", len(valid_df))
print("Testing:", len(test_df))

print("\nValidation shape:", valid_df.shape)
print("Testing shape:", test_df.shape)

Training: 0
Validation: 650
Testing: 626

Validation shape: (650, 5)
Testing shape: (626, 5)

In [ ]:
print("Validation domains:")
print(valid_df["domain"].value_counts())

print("\nTest domains:")
print(test_df["domain"].value_counts())

Validation domains:
domain
message-like    650
Name: count, dtype: int64

Test domains:
domain
message-like    626
Name: count, dtype: int64

In [ ]:
print("Missing values in validation:")
print(valid_df.isnull().sum())

print("\nMissing values in test:")
print(test_df.isnull().sum())

Missing values in validation:
id        0
split     0
source    0
target    0
domain    0
dtype: int64

Missing values in test:
id        0
split     0
source    0
target    0
domain    0
dtype: int64

In [ ]:
print("Training:", len(train_df))
print("Validation:", len(valid_df))
print("Testing:", len(test_df))

print("\nValidation shape:", valid_df.shape)
print("Testing shape:", test_df.shape)

print("\nValidation domains:")
print(valid_df["domain"].value_counts())

print("\nTest domains:")
print(test_df["domain"].value_counts())

print("\nMissing values in validation:")
print(valid_df.isnull().sum())

print("\nMissing values in test:")
print(test_df.isnull().sum())

Training: 0
Validation: 650
Testing: 626

Validation shape: (650, 5)
Testing shape: (626, 5)

Validation domains:
domain
message-like    650
Name: count, dtype: int64

Test domains:
domain
message-like    626
Name: count, dtype: int64

Missing values in validation:
id        0
split     0
source    0
target    0
domain    0
dtype: int64

Missing values in test:
id        0
split     0
source    0
target    0
domain    0
dtype: int64

In [ ]:
print("Training:", len(train_df))
print("Validation:", len(valid_df))
print("Testing:", len(test_df))

print("\nValidation shape:", valid_df.shape)
print("Testing shape:", test_df.shape)

print("\nValidation domains:")
print(valid_df["domain"].value_counts())

print("\nTest domains:")
print(test_df["domain"].value_counts())

print("\nMissing values in validation:")
print(valid_df.isnull().sum())

print("\nMissing values in test:")
print(test_df.isnull().sum())

Training: 0
Validation: 650
Testing: 626

Validation shape: (650, 5)
Testing shape: (626, 5)

Validation domains:
domain
message-like    650
Name: count, dtype: int64

Test domains:
domain
message-like    626
Name: count, dtype: int64

Missing values in validation:
id        0
split     0
source    0
target    0
domain    0
dtype: int64

Missing values in test:
id        0
split     0
source    0
target    0
domain    0
dtype: int64

In [ ]:
print("Training columns:")
print(train_df.columns.tolist())

print("\nValidation columns:")
print(valid_df.columns.tolist())

print("\nTesting columns:")
print(test_df.columns.tolist())

Training columns:
['id', 'split', 'source', 'target', 'domain']

Validation columns:
['id', 'split', 'source', 'target', 'domain']

Testing columns:
['id', 'split', 'source', 'target', 'domain']

Empty DataFrame
Columns: [id, split, source, target, domain]
Index: []

In [ ]:
print("Training shape:", train_df.shape)
print("Validation shape:", valid_df.shape)
print("Testing shape:", test_df.shape)

print("\nTraining rows:", len(train_df))
print("Validation rows:", len(valid_df))
print("Testing rows:", len(test_df))

Training shape: (0, 5)
Validation shape: (650, 5)
Testing shape: (626, 5)

Training rows: 0
Validation rows: 650
Testing rows: 626

In [ ]:
print(df["split"].unique())

KeyError: 'split'

In [ ]:
print("train_df columns:")
print(train_df.columns.tolist())

print("\nvalid_df columns:")
print(valid_df.columns.tolist())

print("\ntest_df columns:")
print(test_df.columns.tolist())

train_df columns:
['id', 'split', 'source', 'target', 'domain']

valid_df columns:
['id', 'split', 'source', 'target', 'domain']

test_df columns:
['id', 'split', 'source', 'target', 'domain']

In [ ]:
print("\nFirst validation row:")
print(valid_df.iloc[0])

First validation row:
id                                                    dev_1
split                                                   dev
source    So I think we can not live if old people could...
target    So I think we would not be alive if our ancest...
domain                                         message-like
Name: 0, dtype: object

In [ ]:
print("Training columns:")
print(train_df.columns.tolist())

print("\nValidation split values:")
print(valid_df["split"].value_counts())

print("\nTesting split values:")
print(test_df["split"].value_counts())

Training columns:
['id', 'split', 'source', 'target', 'domain']

Validation split values:
split
dev    650
Name: count, dtype: int64

Testing split values:
split
test    626
Name: count, dtype: int64

In [ ]:
print(df.columns.tolist())
print(df["split"].value_counts())

['Original', 'Corrected', 'Error', 'Suggestion', 'Category', 'Confidence']

KeyError: 'split'

In [ ]:
print("DataFrames currently available:")

for name, value in globals().items():
    if hasattr(value, "columns"):
        print(name, "→", value.shape, "→", value.columns.tolist())

DataFrames currently available:

RuntimeError: dictionary changed size during iteration

In [ ]:
print("DataFrames currently available:\n")

for name, value in list(globals().items()):
    if hasattr(value, "columns") and hasattr(value, "shape"):
        print(name, "→", value.shape, "→", value.columns.tolist())

DataFrames currently available:

_ → (0, 5) → ['id', 'split', 'source', 'target', 'domain']
__ → (11, 6) → ['Original', 'Corrected', 'Error', 'Suggestion', 'Category', 'Confidence']
df → (11, 6) → ['Original', 'Corrected', 'Error', 'Suggestion', 'Category', 'Confidence']
_25 → (11, 6) → ['Original', 'Corrected', 'Error', 'Suggestion', 'Category', 'Confidence']
train_df → (0, 5) → ['id', 'split', 'source', 'target', 'domain']
valid_df → (650, 5) → ['id', 'split', 'source', 'target', 'domain']
test_df → (626, 5) → ['id', 'split', 'source', 'target', 'domain']
_46 → (0, 5) → ['id', 'split', 'source', 'target', 'domain']

In [ ]:
print(_.shape)
print(_.columns.tolist())
print(_.head())

print("\nSplit values:")
print(_["split"].value_counts(dropna=False))

(0, 5)
['id', 'split', 'source', 'target', 'domain']
Empty DataFrame
Columns: [id, split, source, target, domain]
Index: []

Split values:
Series([], Name: count, dtype: int64)

In [ ]:
print("VALIDATION DATA")
print(valid_df["split"].value_counts())

print("\nTEST DATA")
print(test_df["split"].value_counts())

print("\nValidation example:")
print(valid_df[["source", "target"]].head(3))

VALIDATION DATA
split
dev    650
Name: count, dtype: int64

TEST DATA
split
test    626
Name: count, dtype: int64

Validation example:
                                              source  \
0  So I think we can not live if old people could...
1                                  For not use car .
2  Here was no promise of morning except that we ...

                                              target
0  So I think we would not be alive if our ancest...
1                           Not for use with a car .
2  Here was no promise of morning , except that w...

In [ ]:
from sklearn.model_selection import train_test_split

# Use the 650 dev examples
dev_df = valid_df.copy()

# Split dev data into training (80%) and validation (20%)
train_df, valid_df = train_test_split(
    dev_df,
    test_size=0.20,
    random_state=42
)

print("Training shape:", train_df.shape)
print("Validation shape:", valid_df.shape)
print("Testing shape:", test_df.shape)

Training shape: (520, 5)
Validation shape: (130, 5)
Testing shape: (626, 5)

In [ ]:
print("TRAINING EXAMPLE:")
print(train_df[["source", "target"]].head(3))

print("\nVALIDATION EXAMPLE:")
print(valid_df[["source", "target"]].head(3))

print("\nTESTING EXAMPLE:")
print(test_df[["source", "target"]].head(3))

TRAINING EXAMPLE:
                                                source  \
333  However , I woud prefer traveling by myself wi...
29   And it was very easy to me to understand why h...
553  Brifly , sharing the cost of vecation trip is ...

                                                target
333  However , I would prefer traveling by myself ,...
29   I could very easily understand why he would al...
553  Briefly , sharing the cost of a vacation trip ...

VALIDATION EXAMPLE:
                                                source  \
637  Local communities have the main role of protec...
220  This shows that people are aware of the disadv...
428    and rolling stone gather no mass says proverb .

                                                target
637  Local communities have the main role of protec...
220  This shows that people are aware of the disadv...
428  And a rolling stone gathers no moss , says pro...

TESTING EXAMPLE:
                                              source  \
0  New and new technology has been introduced to ...
1  One possible outcome is that an environmentall...
2  Every person needs to know a bit about math , ...

                                              target
0    New technology has been introduced to society .
1  One possible outcome is that an environmentall...
2  Every person needs to know a bit about math , ...

In [ ]:
# Remove missing values
train_df = train_df.dropna(subset=["source", "target"]).copy()
valid_df = valid_df.dropna(subset=["source", "target"]).copy()
test_df = test_df.dropna(subset=["source", "target"]).copy()

# Remove leading/trailing spaces
train_df["source"] = train_df["source"].str.strip()
train_df["target"] = train_df["target"].str.strip()

valid_df["source"] = valid_df["source"].str.strip()
valid_df["target"] = valid_df["target"].str.strip()

test_df["source"] = test_df["source"].str.strip()
test_df["target"] = test_df["target"].str.strip()

# Remove duplicate source sentences
train_df = train_df.drop_duplicates(subset=["source"])
valid_df = valid_df.drop_duplicates(subset=["source"])
test_df = test_df.drop_duplicates(subset=["source"])

print("Training:", train_df.shape)
print("Validation:", valid_df.shape)
print("Testing:", test_df.shape)

Training: (520, 5)
Validation: (130, 5)
Testing: (626, 5)

In [ ]:
def count_errors(data):
    return (data["source"] != data["target"]).sum()

print("Training sentences needing correction:", count_errors(train_df))
print("Validation sentences needing correction:", count_errors(valid_df))
print("Testing sentences needing correction:", count_errors(test_df))

Training sentences needing correction: 520
Validation sentences needing correction: 130
Testing sentences needing correction: 626

In [ ]:
# Take one sentence from the training dataset
sample_text = train_df.iloc[0]["source"]
expected_text = train_df.iloc[0]["target"]

# Check and correct using LanguageTool
matches = tool.check(sample_text)
predicted_text = language_tool_python.utils.correct(sample_text, matches)

print("Original:")
print(sample_text)

print("\nExpected correction:")
print(expected_text)

print("\nLanguageTool correction:")
print(predicted_text)

Original:
However , I woud prefer traveling by myself with the good prepation filled with joy .

Expected correction:
However , I would prefer traveling by myself , with good preparation , and be filled with joy .

LanguageTool correction:
However, I would prefer traveling by myself with the good predation filled with joy.

In [ ]:
results = []

for i in range(min(20, len(test_df))):
    original = test_df.iloc[i]["source"]
    expected = test_df.iloc[i]["target"]

    matches = tool.check(original)
    predicted = language_tool_python.utils.correct(original, matches)

    results.append({
        "Original": original,
        "Expected": expected,
        "Predicted": predicted,
        "Exact Match": predicted.strip() == expected.strip()
    })

results_df = pd.DataFrame(results)

display(results_df)

,Original,Expected,Predicted,Exact Match
0,New and new technology has been introduced to ...,New technology has been introduced to society .,New and new technology has been introduced to ...,False
1,One possible outcome is that an environmentall...,One possible outcome is that an environmentall...,One possible outcome is that an environmentall...,False
2,"Every person needs to know a bit about math , ...","Every person needs to know a bit about math , ...","Every person needs to know a bit about math, s...",False
3,Disadvantage is parking their car is very diff...,A disadvantage is that parking their cars is v...,Disadvantage is parking their car is very diff...,False
4,Bigger farming are use more chemical product a...,Bigger farming is using more chemical products...,Bigger farming are use more chemical product a...,False
5,"Forexample , My cousin is 12years old .","For example , my cousin is 12 years old .","For example, My cousin is 12 years old.",False
6,"if it does , you will only get some misundrest...","If it does , you will only get some misunderst...","If it does, you will only get some misundersto...",False
7,"Secondly , chimp can also present the capabili...","Secondly , chimps are also capable of learning...","Secondly, chimp can also present the capabilit...",False
8,"Nevertheless , this city is having a big change .","Nevertheless , this city is going through a bi...","Nevertheless, this city is having a big change.",False
9,I think to learn facts is only an evidence if ...,I think to learn facts is only evidence if the...,I think to learn facts is only an evidence if ...,False
10,"Unforturntly , almost older people can not use...","Unfortunately , in spite of its benefits , man...","Unfortunately, almost older people can not use...",False
11,becuse if i see some one did somthing to may s...,Because if I see someone did something that ma...,Because if I see someone did something to May ...,False
12,The government should think about the whole na...,The government should think about all nature .,The government should think about the whole na...,False
13,For me it was great because I need to talk on ...,"For me , it was great because I need to talk o...","For me, it was great because I need to talk on...",False
14,He said in other words that the more flouride ...,He said in other words that the more fluoride ...,He said in other words that the more fluoride ...,False
15,When these people create their new ideas other...,"When these people create their new ideas , oth...",When these people create their new ideas other...,False
16,No ohter transportation concept has been as su...,No other transportation concept has been as su...,No other transportation concept has been as su...,False
17,If they prefer to choose cars than motor bike ...,If they prefer to choose cars than motor bikes...,"If they prefer to choose cars than motorbike, ...",False
18,That 's why he is a legend in these days and p...,That 's why he is a legend in these days and p...,That's why he is a legend in these days and pe...,False
19,"for example , in math club , teachers usually ...","In math club for example , teachers usually sh...","For example, in math club, teachers usually te...",False

In [ ]:
print("Exact matches:",
      results_df["Exact Match"].sum())

print("Total sentences:",
      len(results_df))

print("Exact-match accuracy:",
      results_df["Exact Match"].mean() * 100, "%")

Exact matches: 0
Total sentences: 20
Exact-match accuracy: 0.0 %

In [ ]:
import re

def normalize_text(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()


def word_accuracy(original, predicted, expected):
    original_words = set(normalize_text(original).split())
    predicted_words = set(normalize_text(predicted).split())
    expected_words = set(normalize_text(expected).split())

    # Words that the reference correction added
    needed_words = expected_words - original_words

    # Words that LanguageTool added
    predicted_added = predicted_words - original_words

    if len(needed_words) == 0:
        return 1.0

    correctly_added = needed_words.intersection(predicted_added)

    return len(correctly_added) / len(needed_words)

In [ ]:
results_df["Word Accuracy"] = results_df.apply(
    lambda row: word_accuracy(
        row["Original"],
        row["Predicted"],
        row["Expected"]
    ),
    axis=1
)

print(
    "Average Word-Level Accuracy:",
    results_df["Word Accuracy"].mean() * 100,
    "%"
)

display(
    results_df[
        ["Original", "Expected", "Predicted", "Word Accuracy"]
    ].head(10)
)

Average Word-Level Accuracy: 42.74603174603174 %

,Original,Expected,Predicted,Word Accuracy
0,New and new technology has been introduced to ...,New technology has been introduced to society .,New and new technology has been introduced to ...,1.000000
1,One possible outcome is that an environmentall...,One possible outcome is that an environmentall...,One possible outcome is that an environmentall...,1.000000
2,"Every person needs to know a bit about math , ...","Every person needs to know a bit about math , ...","Every person needs to know a bit about math, s...",0.000000
3,Disadvantage is parking their car is very diff...,A disadvantage is that parking their cars is v...,Disadvantage is parking their car is very diff...,0.000000
4,Bigger farming are use more chemical product a...,Bigger farming is using more chemical products...,Bigger farming are use more chemical product a...,0.000000
5,"Forexample , My cousin is 12years old .","For example , my cousin is 12 years old .","For example, My cousin is 12 years old.",1.000000
6,"if it does , you will only get some misundrest...","If it does , you will only get some misunderst...","If it does, you will only get some misundersto...",1.000000
7,"Secondly , chimp can also present the capabili...","Secondly , chimps are also capable of learning...","Secondly, chimp can also present the capabilit...",0.111111
8,"Nevertheless , this city is having a big change .","Nevertheless , this city is going through a bi...","Nevertheless, this city is having a big change.",0.000000
9,I think to learn facts is only an evidence if ...,I think to learn facts is only evidence if the...,I think to learn facts is only an evidence if ...,0.500000

In [ ]:
def correction_success(original, predicted):
    original_n = normalize_text(original)
    predicted_n = normalize_text(predicted)

    # If nothing changed
    if original_n == predicted_n:
        return 0

    return 1


results_df["Correction Made"] = results_df.apply(
    lambda row: correction_success(
        row["Original"],
        row["Predicted"]
    ),
    axis=1
)

print(
    "Sentences where LanguageTool made a correction:",
    results_df["Correction Made"].sum()
)

print(
    "Correction rate:",
    results_df["Correction Made"].mean() * 100,
    "%"
)

Sentences where LanguageTool made a correction: 10
Correction rate: 50.0 %

In [ ]:
for i, row in results_df.iterrows():

    print("=" * 80)
    print("Example:", i)

    print("\nOriginal:")
    print(row["Original"])

    print("\nExpected:")
    print(row["Expected"])

    print("\nLanguageTool:")
    print(row["Predicted"])

    print("\nWord Accuracy:",
          round(row["Word Accuracy"] * 100, 2), "%")

================================================================================
Example: 0

Original:
New and new technology has been introduced to the society .

Expected:
New technology has been introduced to society .

LanguageTool:
New and new technology has been introduced to the society.

Word Accuracy: 100.0 %
================================================================================
Example: 1

Original:
One possible outcome is that an environmentally-induced reduction in motorization levels in the richer countries will outweigh any rise in motorization levels in the poorer countries .

Expected:
One possible outcome is that an environmentally-induced reduction in motorization levels in richer countries will outweigh any rise in motorization levels in poorer countries .

LanguageTool:
One possible outcome is that an environmentally-induced reduction in motorization levels in the richer countries will outweigh any rise in motorization levels in the poorer countries.

Word Accuracy: 100.0 %
================================================================================
Example: 2

Original:
Every person needs to know a bit about math , sciences , arts , literature and history in order to stand out in society .

Expected:
Every person needs to know a bit about math , science , art , literature and history in order to stand out in society .

LanguageTool:
Every person needs to know a bit about math, sciences, arts, literature and history in order to stand out in society.

Word Accuracy: 0.0 %
================================================================================
Example: 3

Original:
Disadvantage is parking their car is very difficult .

Expected:
A disadvantage is that parking their cars is very difficult .

LanguageTool:
Disadvantage is parking their car is very difficult.

Word Accuracy: 0.0 %
================================================================================
Example: 4

Original:
Bigger farming are use more chemical product and substance to feed fish .

Expected:
Bigger farming is using more chemical products and substances to feed fish .

LanguageTool:
Bigger farming are use more chemical product and substance to feed fish.

Word Accuracy: 0.0 %
================================================================================
Example: 5

Original:
Forexample , My cousin is 12years old .

Expected:
For example , my cousin is 12 years old .

LanguageTool:
For example, My cousin is 12 years old.

Word Accuracy: 100.0 %
================================================================================
Example: 6

Original:
if it does , you will only get some misundrestood idea about that acticle but not the original one .

Expected:
If it does , you will only get some misunderstood idea about that article but not the original one .

LanguageTool:
If it does, you will only get some misunderstood idea about that article but not the original one.

Word Accuracy: 100.0 %
================================================================================
Example: 7

Original:
Secondly , chimp can also present the capability for grammer which means it can demonstrate the ability to combine words and be able to use grammatical constructions .

Expected:
Secondly , chimps are also capable of learning grammar , meaning they can demonstrate the ability to combine words and utilize grammatical constructions .

LanguageTool:
Secondly, chimp can also present the capability for grammar which means it can demonstrate the ability to combine words and be able to use grammatical constructions.

Word Accuracy: 11.11 %
================================================================================
Example: 8

Original:
Nevertheless , this city is having a big change .

Expected:
Nevertheless , this city is going through a big change .

LanguageTool:
Nevertheless, this city is having a big change.

Word Accuracy: 0.0 %
================================================================================
Example: 9

Original:
I think to learn facts is only an evidence if the students can work hard and if they are able to keep every detailled information as tought , but it 's definitly not an evidence for their intelligence .

Expected:
I think to learn facts is only evidence if the students can work hard and if they are able to keep every detailed information taught , but it 's definitely not evidence of their intelligence .

LanguageTool:
I think to learn facts is only an evidence if the students can work hard and if they are able to keep every detailed information as thought, but it's definitely not an evidence for their intelligence.

Word Accuracy: 50.0 %
================================================================================
Example: 10

Original:
Unforturntly , almost older people can not use internet , in spite of benefit of internet .

Expected:
Unfortunately , in spite of its benefits , many older people can not use the Internet .

LanguageTool:
Unfortunately, almost older people can not use internet, in spite of benefit of internet.

Word Accuracy: 20.0 %
================================================================================
Example: 11

Original:
becuse if i see some one did somthing to may safe me time and engy and it wok 's i will do it .

Expected:
Because if I see someone did something that may save me time and energy and it works , I will do it .

LanguageTool:
Because if I see someone did something to May save me time and envy and its wok's I will do it.

Word Accuracy: 57.14 %
================================================================================
Example: 12

Original:
The government should think about the whole nature .

Expected:
The government should think about all nature .

LanguageTool:
The government should think about the whole nature.

Word Accuracy: 0.0 %
================================================================================
Example: 13

Original:
For me it was great because I need to talk on the phone locally and nationally for long periods of time .

Expected:
For me , it was great because I need to talk on the phone locally and nationally for long periods of time .

LanguageTool:
For me, it was great because I need to talk on the phone locally and nationally for long periods of time.

Word Accuracy: 100.0 %
================================================================================
Example: 14

Original:
He said in other words that the more flouride may create damage in human body , specifically the bone .

Expected:
He said in other words that the more fluoride may create damage in the human body , specifically the bone .

LanguageTool:
He said in other words that the more fluoride may create damage in human body, specifically the bone.

Word Accuracy: 100.0 %
================================================================================
Example: 15

Original:
When these people create their new ideas others often look very strange on them .

Expected:
When these people create their new ideas , others often look very strange to them .

LanguageTool:
When these people create their new ideas others often look very strange on them.

Word Accuracy: 0.0 %
================================================================================
Example: 16

Original:
No ohter transportation concept has been as successful as the car , not only because the goog street and highway system throughout the United States and Europe , but only because off the fact , that people love their cars .

Expected:
No other transportation concept has been as successful as the car , not only because they can go on the street and highway system throughout the United States and Europe , but because of the fact that people love their cars .

LanguageTool:
No other transportation concept has been as successful as the car, not only because the good street and highway system throughout the United States and Europe, but only because off the fact, that people love their cars.

Word Accuracy: 16.67 %
================================================================================
Example: 17

Original:
If they prefer to choose cars than motor bike , that means there will be many cars .

Expected:
If they prefer to choose cars than motor bikes , that means there will be many cars .

LanguageTool:
If they prefer to choose cars than motorbike, that means there will be many cars.

Word Accuracy: 0.0 %
================================================================================
Example: 18

Original:
That 's why he is a legend in these days and people repect him .

Expected:
That 's why he is a legend in these days and people respect him .

LanguageTool:
That's why he is a legend in these days and people respect him.

Word Accuracy: 100.0 %
================================================================================
Example: 19

Original:
for example , in math club , teachers usually teach us how to solve a math problem using vary ways .

Expected:
In math club for example , teachers usually show how to solve a math problem in different ways .

LanguageTool:
For example, in math club, teachers usually teach us how to solve a math problem using vary ways.

Word Accuracy: 0.0 %

In [ ]:
text = train_df.iloc[0]["source"]

doc = nlp(text)

for token in doc:
    print(
        f"Word: {token.text:15} "
        f"POS: {token.pos_:8} "
        f"Lemma: {token.lemma_:15}"
    )

Word: However         POS: ADV      Lemma: however
Word: ,               POS: PUNCT    Lemma: ,
Word: I               POS: PRON     Lemma: I
Word: woud            POS: VERB     Lemma: woud
Word: prefer          POS: VERB     Lemma: prefer
Word: traveling       POS: VERB     Lemma: travel
Word: by              POS: ADP      Lemma: by
Word: myself          POS: PRON     Lemma: myself
Word: with            POS: ADP      Lemma: with
Word: the             POS: DET      Lemma: the
Word: good            POS: ADJ      Lemma: good
Word: prepation       POS: NOUN     Lemma: prepation
Word: filled          POS: VERB     Lemma: fill
Word: with            POS: ADP      Lemma: with
Word: joy             POS: NOUN     Lemma: joy
Word: .               POS: PUNCT    Lemma: .

In [ ]:
print("Original sentence:")
print(text)

print("\nNLP Analysis:")
print("-" * 60)

for token in doc:
    print(
        f"{token.text:15} | "
        f"POS: {token.pos_:8} | "
        f"Lemma: {token.lemma_:15}"
    )

Original sentence:
However , I woud prefer traveling by myself with the good prepation filled with joy .

NLP Analysis:
------------------------------------------------------------
However         | POS: ADV      | Lemma: however
,               | POS: PUNCT    | Lemma: ,
I               | POS: PRON     | Lemma: I
woud            | POS: VERB     | Lemma: woud
prefer          | POS: VERB     | Lemma: prefer
traveling       | POS: VERB     | Lemma: travel
by              | POS: ADP      | Lemma: by
myself          | POS: PRON     | Lemma: myself
with            | POS: ADP      | Lemma: with
the             | POS: DET      | Lemma: the
good            | POS: ADJ      | Lemma: good
prepation       | POS: NOUN     | Lemma: prepation
filled          | POS: VERB     | Lemma: fill
with            | POS: ADP      | Lemma: with
joy             | POS: NOUN     | Lemma: joy
.               | POS: PUNCT    | Lemma: .

In [ ]:
import language_tool_python
import spacy

# Load spaCy
nlp = spacy.load("en_core_web_sm")

# Load LanguageTool
tool = language_tool_python.LanguageTool("en-US")


# -----------------------------
# Error Category
# -----------------------------
def categorize_error(match):
    message = match.message.lower()

    if "pronoun" in message and "third-person" in message:
        return "Subject-Verb Agreement"

    if "subject" in message and "verb" in message:
        return "Subject-Verb Agreement"

    if "spelling" in message or "misspelled" in message:
        return "Spelling"

    if "article" in message or "determiner" in message:
        return "Article/Determiner"

    if "preposition" in message:
        return "Preposition"

    if "tense" in message or "past tense" in message:
        return "Verb Tense"

    if "punctuation" in message:
        return "Punctuation"

    if "capital" in message:
        return "Capitalization"

    return "Other Grammar"


# -----------------------------
# Confidence Score
# -----------------------------
def calculate_confidence(match):
    score = 50

    if len(match.replacements) == 1:
        score += 30
    elif len(match.replacements) == 2:
        score += 20
    elif len(match.replacements) >= 3:
        score += 10

    if match.message:
        score += 10

    return min(score, 100)


# -----------------------------
# Combined NLP Analysis
# -----------------------------
def analyze_with_nlp(text):

    # 1. spaCy analysis
    doc = nlp(text)

    tokens = []

    for token in doc:
        tokens.append({
            "word": token.text,
            "pos": token.pos_,
            "lemma": token.lemma_
        })

    # 2. LanguageTool analysis
    matches = tool.check(text)

    errors = []

    for match in matches:

        error = text[
            match.offset:
            match.offset + match.error_length
        ]

        errors.append({
            "error": error,
            "suggestions": match.replacements[:3],
            "category": categorize_error(match),
            "confidence": calculate_confidence(match),
            "message": match.message,
            "position": match.offset
        })

    # 3. Correct sentence
    corrected_text = language_tool_python.utils.correct(
        text,
        matches
    )

    # 4. Return result
    return {
        "original": text,
        "corrected": corrected_text,
        "tokens": tokens,
        "errors": errors,
        "total_errors": len(errors)
    }

print("Combined NLP function created successfully!")

Combined NLP function created successfully!

In [ ]:
sample = train_df.iloc[0]["source"]

result = analyze_with_nlp(sample)

print("Original:")
print(result["original"])

print("\nCorrected:")
print(result["corrected"])

print("\nTotal Errors:")
print(result["total_errors"])

print("\nErrors Found:")

for error in result["errors"]:
    print("\nError:", error["error"])
    print("Suggestion:", error["suggestions"])
    print("Category:", error["category"])
    print("Confidence:", error["confidence"], "%")
    print("Message:", error["message"])

Original:
However , I woud prefer traveling by myself with the good prepation filled with joy .

Corrected:
However, I would prefer traveling by myself with the good predation filled with joy.

Total Errors:
4

Errors Found:

Error:  ,
Suggestion: [',']
Category: Other Grammar
Confidence: 90 %
Message: Put a space after the comma, but not before the comma.

Error: woud
Suggestion: ['would', 'word', 'wood']
Category: Spelling
Confidence: 70 %
Message: Possible spelling mistake found.

Error: prepation
Suggestion: ['predation']
Category: Spelling
Confidence: 90 %
Message: Possible spelling mistake found.

Error:  .
Suggestion: ['.']
Category: Other Grammar
Confidence: 90 %
Message: Don’t put a space before the full stop.

In [ ]:
def categorize_error(match):
    message = match.message.lower()
    rule = match.rule_id.lower() if hasattr(match, "rule_id") else ""

    # Punctuation
    if (
        "comma" in message
        or "full stop" in message
        or "punctuation" in message
        or "punctuation" in rule
    ):
        return "Punctuation"

    # Spelling
    if (
        "spelling mistake" in message
        or "misspelled" in message
        or "possible spelling" in message
    ):
        return "Spelling"

    # Subject-Verb Agreement
    if (
        "subject" in message and "verb" in message
    ) or (
        "third-person" in message
    ):
        return "Subject-Verb Agreement"

    # Articles / Determiners
    if (
        "article" in message
        or "determiner" in message
    ):
        return "Article/Determiner"

    # Prepositions
    if "preposition" in message:
        return "Preposition"

    # Verb tense
    if (
        "tense" in message
        or "past tense" in message
        or "present tense" in message
    ):
        return "Verb Tense"

    # Capitalization
    if (
        "capital" in message
        or "uppercase" in message
    ):
        return "Capitalization"

    return "Other Grammar"

In [ ]:
result = analyze_with_nlp(sample)

for error in result["errors"]:
    print("\nError:", error["error"])
    print("Suggestion:", error["suggestions"])
    print("Category:", error["category"])
    print("Confidence:", error["confidence"], "%")

Error:  ,
Suggestion: [',']
Category: Punctuation
Confidence: 90 %

Error: woud
Suggestion: ['would', 'word', 'wood']
Category: Spelling
Confidence: 70 %

Error: prepation
Suggestion: ['predation']
Category: Spelling
Confidence: 90 %

Error:  .
Suggestion: ['.']
Category: Punctuation
Confidence: 90 %

In [ ]:
test_results = []

for i, row in test_df.iterrows():

    original = row["source"]
    expected = row["target"]

    result = analyze_with_nlp(original)

    test_results.append({
        "ID": row["id"],
        "Original": original,
        "Expected": expected,
        "Predicted": result["corrected"],
        "Total Errors": result["total_errors"]
    })

test_results_df = pd.DataFrame(test_results)

print("Testing completed!")
print("Total test sentences:", len(test_results_df))

Testing completed!
Total test sentences: 626

In [ ]:
display(test_results_df.head(10))

,ID,Original,Expected,Predicted,Total Errors
0,test_651,New and new technology has been introduced to ...,New technology has been introduced to society .,New and new technology has been introduced to ...,1
1,test_652,One possible outcome is that an environmentall...,One possible outcome is that an environmentall...,One possible outcome is that an environmentall...,1
2,test_653,"Every person needs to know a bit about math , ...","Every person needs to know a bit about math , ...","Every person needs to know a bit about math, s...",4
3,test_654,Disadvantage is parking their car is very diff...,A disadvantage is that parking their cars is v...,Disadvantage is parking their car is very diff...,1
4,test_655,Bigger farming are use more chemical product a...,Bigger farming is using more chemical products...,Bigger farming are use more chemical product a...,1
5,test_656,"Forexample , My cousin is 12years old .","For example , my cousin is 12 years old .","For example, My cousin is 12 years old.",4
6,test_657,"if it does , you will only get some misundrest...","If it does , you will only get some misunderst...","If it does, you will only get some misundersto...",5
7,test_658,"Secondly , chimp can also present the capabili...","Secondly , chimps are also capable of learning...","Secondly, chimp can also present the capabilit...",3
8,test_659,"Nevertheless , this city is having a big change .","Nevertheless , this city is going through a bi...","Nevertheless, this city is having a big change.",2
9,test_660,I think to learn facts is only an evidence if ...,I think to learn facts is only evidence if the...,I think to learn facts is only an evidence if ...,6

In [ ]:
test_results_df["Exact Match"] = (
    test_results_df["Predicted"].str.strip().str.lower()
    ==
    test_results_df["Expected"].str.strip().str.lower()
)

test_results_df["Correction Made"] = (
    test_results_df["Original"].str.strip().str.lower()
    !=
    test_results_df["Predicted"].str.strip().str.lower()
)

print("Total test sentences:", len(test_results_df))

print(
    "Exact matches:",
    test_results_df["Exact Match"].sum()
)

print(
    "Exact-match accuracy:",
    test_results_df["Exact Match"].mean() * 100,
    "%"
)

print(
    "Sentences where LanguageTool made a change:",
    test_results_df["Correction Made"].sum()
)

print(
    "Correction rate:",
    test_results_df["Correction Made"].mean() * 100,
    "%"
)

Total test sentences: 626
Exact matches: 1
Exact-match accuracy: 0.1597444089456869 %
Sentences where LanguageTool made a change: 622
Correction rate: 99.36102236421725 %

In [ ]:
test_results_df["Word Accuracy"] = test_results_df.apply(
    lambda row: word_accuracy(
        row["Original"],
        row["Predicted"],
        row["Expected"]
    ),
    axis=1
)

print(
    "Average Word-Level Accuracy:",
    test_results_df["Word Accuracy"].mean() * 100,
    "%"
)

Average Word-Level Accuracy: 34.89053943926148 %

In [ ]:
print("Lowest word-accuracy examples:")
display(
    test_results_df[
        ["ID", "Original", "Expected", "Predicted", "Word Accuracy"]
    ]
    .sort_values("Word Accuracy")
    .head(10)
)

Lowest word-accuracy examples:

,ID,Original,Expected,Predicted,Word Accuracy
241,test_892,there may be global warming because of lacking...,There may be global warming because of the lac...,There may be global warming because of lacking...,0.0
412,test_1063,Scientists are worried that someday these foss...,Scientists are worried that someday we will de...,Scientists are worried that someday these foss...,0.0
410,test_1061,so my opinion is If friend is stay in the worl...,"So , my opinion is that if the friend stays in...",So my opinion is If friend is stayed in the wo...,0.0
256,test_907,It is better to have a very good understanding...,It is better to have a very good understanding...,It is better to have a very good understanding...,0.0
254,test_905,"Though , in fact , old people can enjoy themse...","Though in fact , old people can enjoy some lig...","Though, in fact, old people can enjoy themselv...",0.0
252,test_903,"Also , students , by paying more attention to ...","Also , students , by paying more attention to ...","Also, students, by paying more attention to un...",0.0
249,test_900,They have espessial diet .,They have a special diet .,They have especial diet.,0.0
247,test_898,television makers just hung academic title on ...,Television makers just hang academic titles on...,Television makers just hung academic title on ...,0.0
246,test_897,"Ther third reason , is that give us the chance...",The third reason is that it gives us the chanc...,"The third reason, is that give us the chance t...",0.0
243,test_894,"Thy are busy in there self , thy dont spend ti...",Thy are busy with themselves and do n't spend ...,"Thy are busy in there self, thy don't spend ti...",0.0

In [ ]:
print("Highest word-accuracy examples:")
display(
    test_results_df[
        ["ID", "Original", "Expected", "Predicted", "Word Accuracy"]
    ]
    .sort_values("Word Accuracy", ascending=False)
    .head(10)
)

Highest word-accuracy examples:

,ID,Original,Expected,Predicted,Word Accuracy
606,test_1257,"This is probably because we are all , in gener...","This is probably because we are all , in gener...","This is probably because we are all, in genera...",1.0
603,test_1254,Becaus we need food .,Because we need food .,Because we need food.,1.0
601,test_1252,"Thus , after you return to the city , you may ...","Thus , after you return to the city , you may ...","Thus, after you return to the city, you may be...",1.0
598,test_1249,And this might propably mean that our knowledg...,And this probably might mean that our knowledg...,And this might probably mean that our knowledg...,1.0
595,test_1246,"However , I think that what students like is m...","However , I think what students like is more i...","However, I think that what students like is mo...",1.0
31,test_682,I am pleased to know intelligent peple and lea...,I am pleased to know intelligent people and le...,I am pleased to know intelligent people and le...,1.0
18,test_669,That 's why he is a legend in these days and p...,That 's why he is a legend in these days and p...,That's why he is a legend in these days and pe...,1.0
590,test_1241,For exsample I like to go to a big city like N...,"For example , I like to go to a big city like ...",For example I like to go to a big city like Ne...,1.0
584,test_1235,The leg of all modern endotherms are undernear...,The leg of all modern endotherms are underneat...,The leg of all modern endotherms are underneat...,1.0
580,test_1231,We had a lot of conversations concerning the f...,We had a lot of conversations concerning the f...,We had a lot of conversations concerning the f...,1.0

In [ ]:
import re
from difflib import SequenceMatcher
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Tokenize words + punctuation
TOKEN_PATTERN = re.compile(r"\w+|[^\w\s]", re.UNICODE)

def get_tokens_with_spans(text):
    tokens = []

    for match in TOKEN_PATTERN.finditer(text):
        tokens.append({
            "token": match.group(),
            "start": match.start(),
            "end": match.end()
        })

    return tokens


def normalize_token(token):
    return token.lower()


def get_reference_error_tokens(source, target):
    """
    Finds source tokens that differ from the reference correction.
    These are treated as reference error tokens.
    """

    source_tokens = [
        normalize_token(x["token"])
        for x in get_tokens_with_spans(source)
    ]

    target_tokens = [
        normalize_token(x["token"])
        for x in get_tokens_with_spans(target)
    ]

    matcher = SequenceMatcher(
        None,
        source_tokens,
        target_tokens
    )

    error_indices = set()

    for tag, i1, i2, j1, j2 in matcher.get_opcodes():

        if tag != "equal":
            for i in range(i1, i2):
                error_indices.add(i)

    return error_indices


def get_predicted_error_tokens(source, matches):
    """
    Finds source tokens covered by LanguageTool errors.
    """

    tokens = get_tokens_with_spans(source)

    predicted_indices = set()

    for match in matches:

        error_start = match.offset
        error_end = match.offset + match.error_length

        for i, token in enumerate(tokens):

            token_start = token["start"]
            token_end = token["end"]

            # Check whether token overlaps LanguageTool error span
            if (
                token_start < error_end
                and token_end > error_start
            ):
                predicted_indices.add(i)

    return predicted_indices


# Store all true/predicted labels
y_true = []
y_pred = []

for _, row in test_df.iterrows():

    source = row["source"]
    target = row["target"]

    # Source tokens
    tokens = get_tokens_with_spans(source)

    # Reference error tokens
    reference_errors = get_reference_error_tokens(
        source,
        target
    )

    # LanguageTool predictions
    matches = tool.check(source)

    predicted_errors = get_predicted_error_tokens(
        source,
        matches
    )

    # Create labels for every source token
    for i in range(len(tokens)):

        if i in reference_errors:
            y_true.append(1)
        else:
            y_true.append(0)

        if i in predicted_errors:
            y_pred.append(1)
        else:
            y_pred.append(0)


# Calculate metrics
accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(
    y_true,
    y_pred,
    zero_division=0
)
recall = recall_score(
    y_true,
    y_pred,
    zero_division=0
)
f1 = f1_score(
    y_true,
    y_pred,
    zero_division=0
)


print("===== ERROR DETECTION EVALUATION =====")
print()
print("Total tokens:", len(y_true))
print()
print("Accuracy :", round(accuracy * 100, 2), "%")
print("Precision:", round(precision * 100, 2), "%")
print("Recall   :", round(recall * 100, 2), "%")
print("F1-Score :", round(f1 * 100, 2), "%")

===== ERROR DETECTION EVALUATION =====

Total tokens: 11897

Accuracy : 77.92 %
Precision: 32.13 %
Recall   : 35.6 %
F1-Score : 33.78 %

In [ ]:
# ==========================================
# STEP 15: FINAL GRAMMAR CHECKER
# ==========================================

def grammar_checker(text):

    # 1. NLP processing
    doc = nlp(text)

    # 2. LanguageTool error detection
    matches = tool.check(text)

    errors = []

    # 3. Extract information about each error
    for match in matches:

        error_text = text[
            match.offset:
            match.offset + match.error_length
        ]

        suggestions = match.replacements[:3]

        category = categorize_error(match)

        confidence = calculate_confidence(match)

        errors.append({
            "error": error_text,
            "suggestions": suggestions,
            "category": category,
            "confidence": confidence,
            "message": match.message,
            "position": match.offset
        })

    # 4. Generate corrected sentence
    corrected_text = language_tool_python.utils.correct(
        text,
        matches
    )

    # 5. Return final result
    return {
        "original": text,
        "corrected": corrected_text,
        "total_errors": len(errors),
        "errors": errors
    }


print("Final grammar checker is ready!")

Final grammar checker is ready!

In [ ]:
text = "She go to school every day."

result = grammar_checker(text)

print("Original:")
print(result["original"])

print("\nCorrected:")
print(result["corrected"])

print("\nTotal Errors:")
print(result["total_errors"])

print("\nError Details:")

for i, error in enumerate(result["errors"], start=1):

    print(f"\nError {i}")
    print("Error       :", error["error"])
    print("Suggestion  :", error["suggestions"])
    print("Category    :", error["category"])
    print("Confidence  :", error["confidence"], "%")
    print("Message     :", error["message"])

Original:
She go to school every day.

Corrected:
She goes to school every day.

Total Errors:
1

Error Details:

Error 1
Error       : go
Suggestion  : ['goes', 'went']
Category    : Subject-Verb Agreement
Confidence  : 80 %
Message     : The pronoun ‘She’ is usually used with a third-person or a past tense verb.

In [ ]:
test_sentences = [
    "She go to school every day.",
    "He eat rice yesterday.",
    "I has a new book.",
    "They is playing football.",
    "I am go to college.",
    "He don't like coffee.",
    "Forexample , I like football.",
    "She have two brother."
]

for sentence in test_sentences:

    result = grammar_checker(sentence)

    print("=" * 70)

    print("Original :", result["original"])
    print("Corrected:", result["corrected"])
    print("Errors   :", result["total_errors"])

    for error in result["errors"]:

        print(
            f"  {error['error']} "
            f"→ {error['suggestions']} "
            f"| {error['category']} "
            f"| {error['confidence']}%"
        )

======================================================================
Original : She go to school every day.
Corrected: She goes to school every day.
Errors   : 1
  go → ['goes', 'went'] | Subject-Verb Agreement | 80%
======================================================================
Original : He eat rice yesterday.
Corrected: He eats rice yesterday.
Errors   : 1
  eat → ['eats', 'ate'] | Subject-Verb Agreement | 80%
======================================================================
Original : I has a new book.
Corrected: I have a new book.
Errors   : 1
  has → ['have'] | Other Grammar | 90%
======================================================================
Original : They is playing football.
Corrected: They are playing football.
Errors   : 1
  is → ['are', 'were'] | Subject-Verb Agreement | 80%
======================================================================
Original : I am go to college.
Corrected: I am going to college.
Errors   : 1
  I am go → ['I am going'] | Other Grammar | 90%
======================================================================
Original : He don't like coffee.
Corrected: He doesn't like coffee.
Errors   : 1
  do → ['does', 'did'] | Subject-Verb Agreement | 80%
======================================================================
Original : Forexample , I like football.
Corrected: For example, I like football.
Errors   : 2
  Forexample → ['For example', 'Forex ample'] | Spelling | 80%
   , → [','] | Punctuation | 90%
======================================================================
Original : She have two brother.
Corrected: She has two brethren.
Errors   : 2
  have → ['has', 'had'] | Subject-Verb Agreement | 80%
  brother → ['brethren', 'brothers'] | Other Grammar | 80%

In [ ]:
def grammar_checker_table(text):

    result = grammar_checker(text)

    rows = []

    for error in result["errors"]:

        rows.append({
            "Error": error["error"],
            "Suggestion": ", ".join(error["suggestions"]),
            "Category": error["category"],
            "Confidence": f"{error['confidence']}%",
            "Explanation": error["message"]
        })

    if rows:
        return pd.DataFrame(rows)

    return pd.DataFrame(
        columns=[
            "Error",
            "Suggestion",
            "Category",
            "Confidence",
            "Explanation"
        ]
    )

In [ ]:
text = "She go to school every day."

result = grammar_checker(text)

print("==========================================")
print("       AI GRAMMAR CHECKER RESULT")
print("==========================================")

print("\nOriginal Text:")
print(result["original"])

print("\nCorrected Text:")
print(result["corrected"])

print("\nTotal Errors:", result["total_errors"])

print("\nError Analysis:")

if result["errors"]:

    for i, error in enumerate(result["errors"], 1):

        print(f"\n{i}. Error:", error["error"])
        print("   Suggestion:", error["suggestions"])
        print("   Category:", error["category"])
        print("   Confidence:", str(error["confidence"]) + "%")
        print("   Explanation:", error["message"])

else:

    print("No errors found.")

==========================================
       AI GRAMMAR CHECKER RESULT
==========================================

Original Text:
She go to school every day.

Corrected Text:
She goes to school every day.

Total Errors: 1

Error Analysis:

1. Error: go
   Suggestion: ['goes', 'went']
   Category: Subject-Verb Agreement
   Confidence: 80%
   Explanation: The pronoun ‘She’ is usually used with a third-person or a past tense verb.

In [ ]:
!pip install -q fastapi uvicorn nest-asyncio

In [ ]:
import nest_asyncio

nest_asyncio.apply()

print("FastAPI environment ready!")

FastAPI environment ready!

In [ ]:
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(
    title="AI Grammar Checker API",
    description="Grammar and spelling correction using NLP",
    version="1.0"
)


class TextInput(BaseModel):
    text: str


@app.get("/")
def home():
    return {
        "message": "AI Grammar Checker API is running"
    }


@app.post("/check")
def check_grammar(data: TextInput):

    result = grammar_checker(data.text)

    return result

In [ ]:
import uvicorn
import threading

def run_api():
    uvicorn.run(
        app,
        host="0.0.0.0",
        port=8000
    )

api_thread = threading.Thread(
    target=run_api,
    daemon=True
)

api_thread.start()

print("FastAPI server started on port 8000")

FastAPI server started on port 8000

In [ ]:
import nest_asyncio
import uvicorn
import threading

nest_asyncio.apply()

def run_api():
    uvicorn.run(
        app,
        host="127.0.0.1",
        port=8000
    )

api_thread = threading.Thread(
    target=run_api,
    daemon=True
)

api_thread.start()

print("FastAPI server starting...")

FastAPI server starting...

Exception in thread Thread-5 (run_api):
Traceback (most recent call last):
  File "/usr/lib/python3.13/threading.py", line 1044, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/usr/lib/python3.13/threading.py", line 995, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipykernel_3016/3529795573.py", line 8, in run_api
    uvicorn.run(
    ~~~~~~~~~~~^
        app,
        ^^^^
        host="127.0.0.1",
        ^^^^^^^^^^^^^^^^^
        port=8000
        ^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/uvicorn/main.py", line 632, in run
    server.run()
    ~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/dist-packages/uvicorn/server.py", line 86, in run
    return asyncio_run(self.serve(sockets=sockets), loop_factory=self.config.get_loop_factory())
TypeError: _patch_asyncio.<locals>.run() got an unexpected keyword argument 'loop_factory'

In [ ]:
import requests

response = requests.get("http://127.0.0.1:8000/")

print("Status Code:", response.status_code)
print("Response:", response.json())

ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x78f754cfa250>: Failed to establish a new connection: [Errno 111] Connection refused'))

In [ ]:
import nest_asyncio
import uvicorn

nest_asyncio.apply()

print("Starting FastAPI...")

Starting FastAPI...

In [ ]:
uvicorn.run(
    app,
    host="127.0.0.1",
    port=8000
)

TypeError: _patch_asyncio.<locals>.run() got an unexpected keyword argument 'loop_factory'

In [ ]:
!pip install -q "uvicorn==0.30.6"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 3.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 2.7.1 requires uvicorn<1,>=0.34, but you have uvicorn 0.30.6 which is incompatible.

In [ ]:
!pip install -q "uvicorn>=0.34,<1"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.4/87.4 kB 1.6 MB/s eta 0:00:00

In [ ]:
import uvicorn

print("Uvicorn version:", uvicorn.__version__)

Uvicorn version: 0.53.0

In [ ]:
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(
    title="AI Grammar Checker API",
    description="Grammar and spelling correction using NLP",
    version="1.0"
)


class TextInput(BaseModel):
    text: str


@app.get("/")
def home():
    return {
        "message": "AI Grammar Checker API is running"
    }


@app.post("/check")
def check_grammar(data: TextInput):
    return grammar_checker(data.text)


print("FastAPI app created successfully!")

FastAPI app created successfully!

In [ ]:
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(
    title="AI Grammar Checker API",
    description="Grammar and spelling correction using NLP",
    version="1.0"
)


class TextInput(BaseModel):
    text: str


@app.get("/")
def home():
    return {
        "message": "AI Grammar Checker API is running"
    }


@app.post("/check")
def check_grammar(data: TextInput):
    return grammar_checker(data.text)


print("FastAPI app created successfully!")

FastAPI app created successfully!

In [ ]:
import uvicorn
import threading
import time

def run_api():
    uvicorn.run(
        app,
        host="127.0.0.1",
        port=8000
    )

api_thread = threading.Thread(
    target=run_api,
    daemon=True
)

api_thread.start()

time.sleep(3)

print("FastAPI server started!")

INFO:     Started server process [18596]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('127.0.0.1', 8000): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.

FastAPI server started!

In [ ]:
import requests

response = requests.get(
    "http://127.0.0.1:8000/"
)

print("Status Code:", response.status_code)
print("Response:", response.json())

INFO:     127.0.0.1:41718 - "GET / HTTP/1.1" 200 OK
Status Code: 200
Response: {'message': 'AI Grammar Checker API is running'}

In [ ]:
response = requests.post(
    "http://127.0.0.1:8000/check",
    json={
        "text": "She go to school every day."
    }
)

print("Status Code:", response.status_code)
print(response.json())

INFO:     127.0.0.1:55656 - "POST /check HTTP/1.1" 500 Internal Server Error

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 422, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/uvicorn/middleware/proxy_headers.py", line 63, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/applications.py", line 1163, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/applications.py", line 96, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/routing.py", line 670, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 2734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 1281, in handle
    await super().handle(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/routing.py", line 280, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 158, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.13/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 144, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 706, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/fastapi/routing.py", line 354, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/anyio/to_thread.py", line 65, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/anyio/_backends/_asyncio.py", line 2706, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/anyio/_backends/_asyncio.py", line 1100, in run
    result = context.run(func, *args)
  File "/tmp/ipykernel_18596/1861266214.py", line 24, in check_grammar
    return grammar_checker(data.text)
           ^^^^^^^^^^^^^^^
NameError: name 'grammar_checker' is not defined

Status Code: 500

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [ ]:
def grammar_checker(text):

    matches = tool.check(text)

    errors = []

    for match in matches:

        error_text = text[
            match.offset:
            match.offset + match.error_length
        ]

        errors.append({
            "error": error_text,
            "suggestions": match.replacements[:3],
            "category": categorize_error(match),
            "confidence": calculate_confidence(match),
            "message": match.message,
            "position": match.offset
        })

    corrected_text = language_tool_python.utils.correct(
        text,
        matches
    )

    return {
        "original": text,
        "corrected": corrected_text,
        "total_errors": len(errors),
        "errors": errors
    }

print("Grammar checker loaded successfully!")

Grammar checker loaded successfully!

In [ ]:
result = grammar_checker(
    "She go to school every day."
)

print(result)

NameError: name 'tool' is not defined

In [ ]:
# ==========================================
# RESTORE NLP ENVIRONMENT
# ==========================================

import language_tool_python
import spacy

# Load spaCy
nlp = spacy.load("en_core_web_sm")

# Load LanguageTool
tool = language_tool_python.LanguageTool("en-US")

print("spaCy loaded:", nlp is not None)
print("LanguageTool loaded:", tool is not None)

spaCy loaded: True
LanguageTool loaded: True

In [ ]:
# ==========================================
# HELPER FUNCTIONS
# ==========================================

def categorize_error(match):

    message = match.message.lower()
    rule = match.rule_id.lower() if hasattr(match, "rule_id") else ""

    # Punctuation
    if (
        "comma" in message
        or "full stop" in message
        or "punctuation" in message
        or "punctuation" in rule
    ):
        return "Punctuation"

    # Spelling
    if (
        "spelling mistake" in message
        or "misspelled" in message
        or "possible spelling" in message
    ):
        return "Spelling"

    # Subject-Verb Agreement
    if (
        ("subject" in message and "verb" in message)
        or "third-person" in message
    ):
        return "Subject-Verb Agreement"

    # Articles / Determiners
    if (
        "article" in message
        or "determiner" in message
    ):
        return "Article/Determiner"

    # Prepositions
    if "preposition" in message:
        return "Preposition"

    # Verb tense
    if (
        "tense" in message
        or "past tense" in message
        or "present tense" in message
    ):
        return "Verb Tense"

    # Capitalization
    if (
        "capital" in message
        or "uppercase" in message
    ):
        return "Capitalization"

    return "Other Grammar"


def calculate_confidence(match):

    score = 50

    if len(match.replacements) == 1:
        score += 30

    elif len(match.replacements) == 2:
        score += 20

    elif len(match.replacements) >= 3:
        score += 10

    if match.message:
        score += 10

    return min(score, 100)


print("Helper functions loaded!")

Helper functions loaded!

In [ ]:
# ==========================================
# FINAL GRAMMAR CHECKER
# ==========================================

def grammar_checker(text):

    matches = tool.check(text)

    errors = []

    for match in matches:

        error_text = text[
            match.offset:
            match.offset + match.error_length
        ]

        errors.append({
            "error": error_text,
            "suggestions": match.replacements[:3],
            "category": categorize_error(match),
            "confidence": calculate_confidence(match),
            "message": match.message,
            "position": match.offset
        })

    corrected_text = language_tool_python.utils.correct(
        text,
        matches
    )

    return {
        "original": text,
        "corrected": corrected_text,
        "total_errors": len(errors),
        "errors": errors
    }


print("Grammar checker loaded!")

Grammar checker loaded!

In [ ]:
result = grammar_checker(
    "She go to school every day."
)

print("Original:", result["original"])
print("Corrected:", result["corrected"])
print("Total Errors:", result["total_errors"])

for error in result["errors"]:

    print("\nError:", error["error"])
    print("Suggestion:", error["suggestions"])
    print("Category:", error["category"])
    print("Confidence:", str(error["confidence"]) + "%")

Original: She go to school every day.
Corrected: She goes to school every day.
Total Errors: 1

Error: go
Suggestion: ['goes', 'went']
Category: Subject-Verb Agreement
Confidence: 80%

In [ ]:
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(
    title="AI Grammar Checker API",
    description="AI-based grammar and spelling checker using NLP",
    version="1.0"
)


class TextInput(BaseModel):
    text: str


@app.get("/")
def home():
    return {
        "message": "AI Grammar Checker API is running"
    }


@app.post("/check")
def check_grammar(data: TextInput):
    return grammar_checker(data.text)


print("FastAPI application created successfully!")

FastAPI application created successfully!

In [ ]:
import uvicorn
import threading
import time

def run_api():
    uvicorn.run(
        app,
        host="127.0.0.1",
        port=8000
    )

api_thread = threading.Thread(
    target=run_api,
    daemon=True
)

api_thread.start()

time.sleep(3)

print("FastAPI server started!")

INFO:     Started server process [18596]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('127.0.0.1', 8000): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.

FastAPI server started!

In [ ]:
import uvicorn
import threading
import time

def run_api():
    uvicorn.run(
        app,
        host="127.0.0.1",
        port=8000
    )

api_thread = threading.Thread(
    target=run_api,
    daemon=True
)

api_thread.start()

time.sleep(3)

print("FastAPI server started!")

INFO:     Started server process [18596]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('127.0.0.1', 8000): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.

FastAPI server started!

In [ ]:
import uvicorn
import threading
import time

def run_api():
    uvicorn.run(
        app,
        host="127.0.0.1",
        port=8000
    )

api_thread = threading.Thread(
    target=run_api,
    daemon=True
)

api_thread.start()

time.sleep(3)

print("FastAPI server started!")

INFO:     Started server process [18596]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('127.0.0.1', 8000): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.

FastAPI server started!

In [ ]:
import requests

response = requests.post(
    "http://127.0.0.1:8000/check",
    json={
        "text": "She go to school every day."
    }
)

print("Status Code:", response.status_code)
print("\nAPI Response:")
print(response.json())

INFO:     127.0.0.1:47696 - "POST /check HTTP/1.1" 200 OK
Status Code: 200

API Response:
{'original': 'She go to school every day.', 'corrected': 'She goes to school every day.', 'total_errors': 1, 'errors': [{'error': 'go', 'suggestions': ['goes', 'went'], 'category': 'Subject-Verb Agreement', 'confidence': 80, 'message': 'The pronoun ‘She’ is usually used with a third-person or a past tense verb.', 'position': 4}]}

In [ ]:
!pip install -q streamlit

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 47.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 61.0 MB/s eta 0:00:00

In [ ]:
%%writefile app.py

import streamlit as st
import requests
import pandas as pd

st.set_page_config(
    page_title="AI Grammar Checker",
    page_icon="📝",
    layout="wide"
)

st.title("📝 AI Grammar Checker")
st.write("Check grammar and spelling using NLP and LanguageTool.")

text = st.text_area(
    "Enter your text:",
    height=200,
    placeholder="Example: She go to school every day."
)

if st.button("Check Grammar"):

    if text.strip() == "":
        st.warning("Please enter some text.")
    else:

        try:
            response = requests.post(
                "http://127.0.0.1:8000/check",
                json={"text": text}
            )

            if response.status_code == 200:

                result = response.json()

                st.subheader("Original Text")
                st.write(result["original"])

                st.subheader("Corrected Text")
                st.success(result["corrected"])

                st.subheader("Analysis")

                col1, col2 = st.columns(2)

                with col1:
                    st.metric(
                        "Total Errors",
                        result["total_errors"]
                    )

                with col2:
                    st.metric(
                        "Status",
                        "Checked"
                    )

                if result["errors"]:

                    st.subheader("Errors Found")

                    table_data = []

                    for error in result["errors"]:
                        table_data.append({
                            "Error": error["error"],
                            "Suggestion": ", ".join(
                                error["suggestions"]
                            ),
                            "Category": error["category"],
                            "Confidence": str(
                                error["confidence"]
                            ) + "%",
                            "Explanation": error["message"]
                        })

                    df = pd.DataFrame(table_data)

                    st.dataframe(
                        df,
                        use_container_width=True
                    )

                else:
                    st.success(
                        "No grammar or spelling errors found!"
                    )

            else:
                st.error(
                    f"API Error: {response.status_code}"
                )

        except Exception as e:
            st.error(
                f"Could not connect to FastAPI: {e}"
            )

Writing app.py

In [ ]:
!streamlit run app.py &>/content/streamlit.log &

In [ ]:
!cat /content/streamlit.log

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-09-29 10:15:26.989 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://35.185.2.217:8501

In [ ]:
!pkill -f streamlit

In [ ]:
!pip install -q pyngrok

In [ ]:
!streamlit run app.py --server.port 8501 > /content/streamlit.log 2>&1 &

In [ ]:
!sleep 5
!cat /content/streamlit.log

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-09-29 10:18:54.112 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://35.185.2.217:8501

In [ ]:
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

Selecting previously unselected package cloudflared.
(Reading database ... 122809 files and directories currently installed.)
Preparing to unpack cloudflared-linux-amd64.deb ...
Unpacking cloudflared (2026.9.3) ...
Setting up cloudflared (2026.9.3) ...
Processing triggers for man-db (2.12.0-4build2) ...

In [ ]:
!streamlit run app.py --server.port 8501 > /content/streamlit.log 2>&1 &

In [ ]:
!sleep 5
!cat /content/streamlit.log

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-09-29 10:20:17.772 Port 8501 is not available

In [ ]:
!cloudflared tunnel --url http://localhost:8501

2026-09-29T10:20:39Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee, are subject to the Cloudflare Online Services Terms of Use (https://www.cloudflare.com/website-terms/), and Cloudflare reserves the right to investigate your use of Tunnels for violations of such terms. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2026-09-29T10:20:39Z INF Requesting new quick Tunnel on trycloudflare.com...
2026-09-29T10:20:45Z INF +--------------------------------------------------------------------------------------------+
2026-09-29T10:20:45Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2026-09-29T10:20:45Z INF |  https://stress-midnight-acquired-raises.trycloudflare.com                                 |
2026-09-29T10:20:45Z INF +--------------------------------------------------------------------------------------------+
2026-09-29T10:20:45Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2026-09-29T10:20:45Z INF Version 2026.9.3 (Checksum 77e26d8d900e0b8469f416239d14b5f296525fdf79fee6f511ef55609e3fbac2)
2026-09-29T10:20:45Z INF GOOS: linux, GOVersion: go1.26.8, GoArch: amd64
2026-09-29T10:20:45Z INF Settings: map[ha-connections:1 protocol:quic url:http://localhost:8501]
2026-09-29T10:20:45Z INF cloudflared will not automatically update if installed by a package manager.
2026-09-29T10:20:45Z INF Generated Connector ID: 956233a5-9be3-4be9-a53d-554efe6528cc
2026-09-29T10:20:45Z INF Initial protocol quic
2026-09-29T10:20:45Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-09-29T10:20:45Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026-09-29T10:20:45Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-09-29T10:20:45Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026-09-29T10:20:45Z INF Starting metrics server on 127.0.0.1:20241/metrics
2026-09-29T10:20:45Z INF Tunnel connection curve preferences: [X25519MLKEM768 CurveID(65074) CurveP256] connIndex=0 event=0 ip=198.41.200.233
2026/09/29 10:20:45 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2026-09-29T10:20:46Z INF Registered tunnel connection connIndex=0 connection=c67d67a3-8718-4ac9-a992-bdf3ed032cca event=0 ip=198.41.200.233 location=atl15 protocol=quic
2026-09-29T10:20:51Z INF +-------------------------------------------------------------------------------------+
2026-09-29T10:20:51Z INF |                               CONNECTIVITY PRE-CHECKS                               |
2026-09-29T10:20:51Z INF +-------------------------------------------------------------------------------------+
2026-09-29T10:20:51Z INF |  COMPONENT         TARGET                     STATUS  DETAILS                       |
2026-09-29T10:20:51Z INF |  DNS Resolution    region1.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-09-29T10:20:51Z INF |  DNS Resolution    region2.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-09-29T10:20:51Z INF |  UDP Connectivity  region1.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-09-29T10:20:51Z INF |  UDP Connectivity  region2.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-09-29T10:20:51Z INF |  TCP Connectivity  region1.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-09-29T10:20:51Z INF |  TCP Connectivity  region2.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-09-29T10:20:51Z INF |  Cloudflare API    api.cloudflare.com:443     PASS    API is reachable              |
2026-09-29T10:20:51Z INF |                                                                                     |
2026-09-29T10:20:51Z INF |  SUMMARY: Environment is healthy. cloudflared will use 'quic' as primary protocol.  |
2026-09-29T10:20:51Z INF +-------------------------------------------------------------------------------------+
2026-09-29T10:20:51Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=b580aea2-e30d-4091-a6f5-a4f01977d147 status=pass target=region1.v2.argotunnel.com
2026-09-29T10:20:51Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=b580aea2-e30d-4091-a6f5-a4f01977d147 status=pass target=region2.v2.argotunnel.com
2026-09-29T10:20:51Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=b580aea2-e30d-4091-a6f5-a4f01977d147 status=pass target=region1.v2.argotunnel.com
2026-09-29T10:20:51Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=b580aea2-e30d-4091-a6f5-a4f01977d147 status=pass target=region2.v2.argotunnel.com
2026-09-29T10:20:51Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=b580aea2-e30d-4091-a6f5-a4f01977d147 status=pass target=region1.v2.argotunnel.com
2026-09-29T10:20:51Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=b580aea2-e30d-4091-a6f5-a4f01977d147 status=pass target=region2.v2.argotunnel.com
2026-09-29T10:20:51Z INF precheck component="Cloudflare API" details="API is reachable" run_id=b580aea2-e30d-4091-a6f5-a4f01977d147 status=pass target=api.cloudflare.com:443
2026-09-29T10:20:51Z INF precheck complete hard_fail=false run_id=b580aea2-e30d-4091-a6f5-a4f01977d147 suggested_protocol=quic
INFO:     127.0.0.1:56648 - "POST /check HTTP/1.1" 200 OK
INFO:     127.0.0.1:60350 - "POST /check HTTP/1.1" 200 OK
INFO:     127.0.0.1:43040 - "POST /check HTTP/1.1" 200 OK
INFO:     127.0.0.1:55424 - "POST /check HTTP/1.1" 200 OK
INFO:     127.0.0.1:58172 - "POST /check HTTP/1.1" 200 OK
INFO:     127.0.0.1:56292 - "POST /check HTTP/1.1" 200 OK